apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: payobills-sbx
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceNamespaces:
  - payobills-sbx
  destinations:
  - namespace: payobills-sbx-sbx
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://payobills.github.io/helm-charts
  - https://github.com/payobills/payobills
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-ui
spec:
  destination:
    namespace: payobills-sbx
    server: https://kubernetes.default.svc
  project: payobills-sbx
  sources:
  - path: ui
    chart: ui
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.2.47
    helm:
      valueFiles:
      - $values/apps/ui/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-bills
spec:
  destination:
    namespace: payobills-sbx
    server: https://kubernetes.default.svc
  project: payobills-sbx
  sources:
  - path: bills
    chart: bills
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.2.16
    helm:
      valueFiles:
      - $values/apps/bills/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-payments
spec:
  destination:
    namespace: payobills-sbx
    server: https://kubernetes.default.svc
  project: payobills-sbx
  sources:
  - path: payments
    chart: payments
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.3.16
    helm:
      valueFiles:
      - $values/apps/payments/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-files
spec:
  destination:
    namespace: payobills-sbx
    server: https://kubernetes.default.svc
  project: payobills-sbx
  sources:
  - path: files
    chart: files
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.2.4
    helm:
      valueFiles:
      - $values/apps/files/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: feat/ui-add-statement-for-bill-parse-transactions
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-bills-parser
spec:
  destination:
    namespace: payobills-sbx
    server: https://kubernetes.default.svc
  project: payobills-sbx
  sources:
  - path: bills-parser
    chart: bills-parser
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.4.2
    helm:
      valueFiles:
      - $values/apps/bills-parser/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true