federation_version: =2.6.0
subgraphs:
  bills:
    routing_url: http://payobills-subgraph-bills.payobills.svc.cluster.local/graphql
    schema:
      subgraph_url: http://localhost:9002/graphql?sdl
  payments:
    routing_url: http://payobills-subgraph-payments.payobills.svc.cluster.local/graphql
    schema:
      subgraph_url: http://localhost:5000/graphql?sdl
  files:
    routing_url: http://payobills-files.payobills.svc.cluster.local/graphql
    schema:
      subgraph_url: http://localhost:9004/graphql
