apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-files
spec:
  destination:
    namespace: payobills
    server: https://kubernetes.default.svc
  project: payobills
  sources:
  - path: files
    chart: files
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.2.4
    helm:
      valueFiles:
      - $values/apps/files/k8s/values.yaml
      values: |
        openTelemetry:
          enabled: "false"
        image:
          repository: ghcr.io/payobills/apps/files
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          tag: "0.2.10"
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

