apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-gateway
spec:
  destination:
    namespace: payobills
    server: https://kubernetes.default.svc
  project: payobills
  sources:
  - path: bills
    chart: bills
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.2.19
    helm:
      values: |
        helpers:
          PROJECT_ROOT: /app
          
        openTelemetry:
          enabled: true

        replicaCount: 1

        image:
          repository: ghcr.io/graphql-hive/gateway
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          tag: "1.8.0"
        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: "payobills-gateway"

        serviceAccount:
          # Specifies whether a service account should be created
          create: true
          # Annotations to add to the service account
          annotations: {}
          # The name of the service account to use.
          # If not set and create is true, a name is generated using the fullname template
          name: ""

        # disableProbes: true
        healthProbes:
          livenessProbe:
            httpGet:
              path: /graphql
              port: http
          readinessProbe:
            httpGet:
              path: /graphql
              port: http

        pod:
          annotations: {}
          command:
          - "node"
          - "bin.mjs"
          - "supergraph"
          - "-c"
          - "/mnt/supergraph-config/gateway.config.js"
          - "/mnt/supergraph-config/supergraph.graphql"
          - "--port"
          - "80"

          env:
          - name: DEBUG
            value: "1"
          - name: ENVIRONMENT
            value: PRODUCTION

          volumeMounts:
          - name: supergraph-config
            mountPath: /mnt/supergraph-config
            readOnly: true

          volumes:
          - name: supergraph-config
            projected:
              sources:
              - configMap:
                  name: supergraph-config
                  items:
                  - key: graphqlSchema
                    path: supergraph.graphql
                  - key: gatewayConfig
                    path: gateway.config.js

        podSecurityContext: {}
          # fsGroup: 2000

        securityContext: {}
          # capabilities:
          #   drop:
          #   - ALL
          # readOnlyRootFilesystem: true
          # runAsNonRoot: true
          # runAsUser: 1000

        service:
          name: bills
          type: ClusterIP
          port: 80

        flags:
          rewrite: false

        ingress:
          enabled: false

        resources: {}
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances charts run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          # requests:
          #   cpu: 100m
          #   memory: 128Mi

        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 100
          targetCPUUtilizationPercentage: 80
          # targetMemoryUtilizationPercentage: 80

        nodeSelector:
          kubernetes.io/hostname: pi

        tolerations: []

        affinity: {}
      valueFiles:
      - $values/apps/payments/k8s/values.yaml
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

