apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payobills-subgraph-payments
spec:
  destination:
    namespace: payobills
    server: https://kubernetes.default.svc
  project: payobills
  sources:
  - path: payments
    chart: payments
    repoURL: https://payobills.github.io/helm-charts
    targetRevision: 0.3.16
    helm:
      valueFiles:
      - $values/apps/payments/k8s/values.yaml
      values: |
        openTelemetry:
          enabled: "false"
        image:
          repository: ghcr.io/payobills/apps/payments
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          tag: "0.6.9"
  - repoURL: 'https://github.com/payobills/payobills.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

